name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Capacitor & dependencies
        run: |
          npm init -y
          npm install @capacitor/cli
          npx cap init "Music Excellence" com.yourname.musicexcellence --web-dir=.
          npm install
          npx cap add ios

      - name: Build IPA
        run: |
          cd ios/App
          xcodebuild -scheme App -sdk iphoneos -configuration Release archive -archivePath $PWD/build/App.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build/ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: MusicExcellence
          path: ios/App/build/ipa